### ISSUE TITLE
General discussion

### ISSUE THREAD

**Issue by Robinlovelace** [saferactive/saferactive#1]
Where should we put issues? How should we organise? 

I suggest general and conceptual issues can go in this repo, while implementation-specific and code issues should go in the shiny/eatlas repos.

**Comment by layik** [comment]
Glad there is mentioning of the eAtlas here :) 

This repo is my vote. But I might delete the eatlas repo and fork it from the original repo and apply the changes and commit. Should have done that when we first set the repo up.

**Comment by Robinlovelace** [comment]
Can we build from geoplumber? Just an idea linking it back to the R package and making it more general, but also happy with building on eatlas if there are +s of doing so. Not fully aware of differences between geoplumber and eatlas, but have an inherent like of the former because it's an R package and I've been more involved in it than the latter.

**Comment by layik** [comment]
The eAtlas is a geoplumber app. The README is now updated.

**Comment by Robinlovelace** [comment]
Could SaferActive be another geoplumber app?

**Comment by Robinlovelace** [comment]
That could start with the same code-base as eAtlas of course, just wondering if generic parts of the eAtlas can become templates in `geoplumber` that make it easier for others to create new apps using the same framework.
