### ISSUE TITLE
Papers / Lit review

### ISSUE THREAD

**Issue by mem48** [saferactive/saferactive#10]
Place to share link images etc on useful methods, visualisations etc

**Comment by Robinlovelace** [comment]
See here a shared Zotero library that we can use to share citations and bibliographic data for the project: https://www.zotero.org/groups/418217/energy-and-transport/collections/9PTF9F44

To add papers you need to first joint the group, which is open to anyone with a Zotero account: https://www.zotero.org/groups/418217/energy-and-transport/

**Comment by layik** [comment]
Roger's link of the IEEEvis Chapter on uncertainty
http://space.ucmerced.edu/Downloads/publications/Uncertainty_Visualization_Padilla_Kay_Hullman_2020.pdf

**Comment by mem48** [comment]
https://www.sciencedirect.com/science/article/pii/S0001457505002095

**Comment by Robinlovelace** [comment]
Looks like an interesting paper, thanks for flagging this @mem48. I've added it to our open library: https://www.zotero.org/groups/418217/energy-and-transport/collections/9PTF9F44/item-list

If anyone finds additional papers do add links here and add them to the Zotero list if you have an account.

**Comment by Robinlovelace** [comment]
Heads-up everyone, especially @joeytalbot and @mem48 I've added a load of recent papers to our shared bibliography here, some really interesting new research coming out in 2020: https://www.zotero.org/groups/418217/energy-and-transport/collections/9PTF9F44/item-list
