### ISSUE TITLE
Generate aggregate per La for the whole dataset

### ISSUE THREAD

**Issue by layik** [saferactive/saferactive#19]
If not duplicate.

Outcome of meeting on 19th June meeting.

**Comment by Robinlovelace** [comment]
This will be really cool, especially if deployed in a simple yet compellingly beautiful and user friendly web app. I suspect that if we do it at the LA level, it could be a self standing JS web-app with no backend. Backend necessary for additional processing on the points but that's another issue...

**Comment by layik** [comment]
So right now, I think we have enough (given #21) and above commit, to deploy:

1. Country wide KSI
2. Click on an area to see heavy json data (must be optimised for example vector tiles)

And go live.

cc @Robinlovelace

**Comment by layik** [comment]
requires a slider for the time (years)

<img width="1533" alt="Screenshot 2020-07-03 at 14 48 40" src="https://user-images.githubusercontent.com/408568/86475297-4e71f500-bd3c-11ea-921c-e4cca9683201.png">

**Comment by Robinlovelace** [comment]
Looking good!

**Comment by Robinlovelace** [comment]
Links to: https://github.com/ropensci/stats19/issues/101

**Comment by layik** [comment]
Not going to open a new ticket but just trying to load the 8.3M records into a Mongodb instance using https://github.com/layik/geocoder. Will report anything interesting.

**Comment by layik** [comment]
Oh that is really disappointing. Almost 1 sec for each row, do not calculate 8.3M seconds.
