### ISSUE TITLE
Descriptive analysis of geographically aggregated crash data

### ISSUE THREAD

**Issue by Robinlovelace** [saferactive/saferactive#56]
Including time series plots and indication of which local authorities have seen most increases and decreases in different types of crashes (primarily walking/cycling KSIs but also walking/cycling all types and disaggregation with other variables such as age).

**Comment by mem48** [comment]
Bad news to LTNs Tower Hamlets had one of the highest increase in crashes

https://github.com/saferactive/saferactive/blob/master/figures/la_top10_increase.png?raw=true

But this will need to be adjusted to reflect joey's work on change in cycling rates

**Comment by Robinlovelace** [comment]
Good to see some results rolling in. Can you run this for upper tier LAs, as discussed in #61?

This is probably a good starting point:

```
ub = "https://github.com/saferactive/saferactive/releases/download/0.1.1/counties_uas_gb_2019_ubc.Rds"
```

**Comment by mem48** [comment]
@Robinlovelace see https://github.com/saferactive/saferactive/blob/master/LA_trends.md let me know what direction you want me to take after lunch

**Comment by Robinlovelace** [comment]
Hi @mem48 see reply here re. another quick task: https://github.com/saferactive/saferactive/issues/61#issuecomment-725451376

**Comment by Robinlovelace** [comment]
Regarding next steps on the LA analysis, can you disaggregate by time (commuter hours/non) and by walking and cycling and by the cross-tabulation of those two? I think a good way of presenting this data is with trend lines for all LAs in grey with selected LAs in colour, as shown here with reproducible example: https://github.com/saferactive/saferactive/issues/14#issuecomment-693615440

![image](https://user-images.githubusercontent.com/1825120/98823622-42085200-242a-11eb-9094-d3c93142489b.png)
