### ISSUE TITLE
Generate vector tiles for rnet_bicycle

### ISSUE THREAD

**Issue by layik** [saferactive/saferactive#60]
Hi all. Just looking at https://github.com/saferactive/saferactive/blob/master/code/rasters-rnet.R but cannot run 
https://github.com/saferactive/saferactive/blob/d227ab29bca7fdb1af4093802364461408628472/code/rasters-rnet.R#L9

Can you point me to where `rnet_national_sf_27700.Rds` is or which script was used to generate it to so I can `source` or regenerate it?

Thanks

**Comment by Robinlovelace** [comment]
Just looking at this @layik, solution soon.

**Comment by Robinlovelace** [comment]
Just updating the data with this:

```
Rscript -e 'piggyback::pb_upload("rnet_national_sf_27700.Rds")'

```

**Comment by Robinlovelace** [comment]
Strange thing: I thought I already updated it. Never mind.

**Comment by Robinlovelace** [comment]
I think this code should now run. Please test and let me know @layik:

https://github.com/saferactive/saferactive/blob/d227ab29bca7fdb1af4093802364461408628472/code/rasters-rnet.R#L2-L13

**Comment by layik** [comment]
Thanks @Robinlovelace, works of course. I will `tippercanoe` it and add the code in same/different file.

**Comment by Robinlovelace** [comment]
Awesome, thanks @layik !

**Comment by layik** [comment]
Generating heatmap using the vector tiles is possible, though mastering it needs time @mem48.

<img width="1442" alt="Screenshot 2020-11-03 at 10 39 17" src="https://user-images.githubusercontent.com/408568/97975542-3630e600-1dc1-11eb-9809-e753c8406b9a.png">

**Comment by layik** [comment]
Both raster + [vector](https://github.com/saferactive/saferactive/releases/download/0.1.1/rnet_bicycle_kkm_yr_vec_tiles.zip) tiles generated in the release (as zip) are "zoom dependent" and have zoom level limit. Refer to their meta files and if you want to use them just be aware or generate your own raster/vector tiles. For the rasters I used the interactive Python tool `gdal2tiles.py` straight from the `.tiff` which is also in the release.
