### ISSUE TITLE
Generate and style rnet_cycling vector tiles

### ISSUE THREAD

**Issue by layik** [saferactive/saferactive#63]
Looks great in this zoom level!
<img width="100%" alt="Screenshot 2020-11-04 at 23 23 10" src="https://user-images.githubusercontent.com/408568/98178568-d6d3f280-1ef4-11eb-8896-f2158854865d.png">

Not so much when zooming out:

<img width="100%" alt="Screenshot 2020-11-04 at 23 24 41" src="https://user-images.githubusercontent.com/408568/98178702-1c90bb00-1ef5-11eb-9f15-909ed627103b.png">

Code chunk will follow though part here and part front end in `-eatlas` repo.

**Comment by layik** [comment]
```r
# make sure you are in an ignored space
getwd()
# 250m segments of cycling potential route network

u = "https://github.com/saferactive/saferactive/releases/download/0.1.1/rnet_split.Rds"
uf = basename(u)
if(!(file.exists(uf))) {
  download.file(u, uf)
}
rnet = readRDS(uf)
names(rnet)
head(rnet)
summary(rnet$bicycle)
rnet_wg86 = sf::st_transform(rnet[,"bicycle"], 4326)
sf::st_write(rnet_wg86, "rnet_cycling.geojson")
# tippecanno it
# tippecanoe -zg --output-to-directory=rnet_cycling --drop-densest-as-needed --no-tile-compression rnet_cycling.geojson
# move to saferactive-eatlas within build
# then play with mapbox api!```

**Comment by layik** [comment]
- API changed
- Vector tiles placed in release for reprex
- Front chanaged
Code pushed.

Notes welcome to make this much better especially with tiling at the zoomed out level

**Comment by Robinlovelace** [comment]
This looks amazing!

**Comment by layik** [comment]
@Robinlovelace can you help me "transform" the route network to a coarser network so we can have better results when zooming out? 

Could you point me to the OSM/osmdata/osmextract where I could get A roads and/or M etc.

Do I make sense?

**Comment by layik** [comment]
OK rephrasing my deleted comment. Would it make sense to generate a coarser route network similar to what slippy maps do to get better tiles when zoomed out? That is aggregating the crashes onto main roads? Not sure if it makes any sense in this case.

**Comment by Robinlovelace** [comment]
> OK rephrasing my deleted comment. Would it make sense to generate a coarser route network similar to what slippy maps do to get better tiles when zoomed out? That is aggregating the crashes onto main roads? Not sure if it makes any sense in this case.

Yes I guess zoom-dependent styling, e.g. using the raster data when zoomed out and the linestring dataset when zoomed in beyond a certain threshold, could look great. We have code to aggregate crashes to the network in #36 but haven't run it for all of UK yet.

**Comment by layik** [comment]
So now able to "arrange" layers within mapbox API so that vector tiles can appear on top of "raster" base layers too. Such as on "satellite" image layer, then becomes another vis challenge.

**Comment by layik** [comment]
See https://map.saferactive.org for a basic implementation of it:
https://map.saferactive.org

New issues in new tickets!
