### ISSUE TITLE
Adjust 'Serious' rates based on CRASH methods from DfT

### ISSUE THREAD

**Issue by Robinlovelace** [saferactive/saferactive#64]
In anticipation of the minihack next week, please share any code/comments here.

Key questions from me: what is the main input dataset that we want to add an adjustment variable to (@joeytalbot may be best placed to answer that)?

And can you paste any code you used to get it working @agila5? May be worthy of creating as a function to go into the `stats19` package as it is a core DfT dataset + method.

**Comment by agila5** [comment]
Here you are :) 

``` r
# packages
library(stats19)
#> Data provided under OGL v3.0. Cite the source and link to:
#> www.nationalarchives.gov.uk/doc/open-government-licence/version/3/
library(ggplot2)

# get stats19 data
crashes_data <- get_stats19(2012, output_format = "sf", silent = TRUE)
#> date and time columns present, creating formatted datetime column
#> 0 rows removed with no coordinates

# download adjustment figures
adj_zip <- tempfile(fileext = ".zip")
download.file(
  url = "http://data.dft.gov.uk/road-accidents-safety-data/accident-and-casualty-adjustment-2004-to-2019.zip", 
  destfile = adj_zip
)
unzip(adj_zip, exdir = tempdir())

# read-in adjustment figures
adj_figures <-read.csv(
  file = paste0(tempdir(), "\\accident_adjustment_lookup_2019.csv"), 
  stringsAsFactors = FALSE, 
  col.names = c("accident_index", "adjusted_serious", "adjusted_slight", "injury_based")
)

# This is the result
head(adj_figures)
#>   accident_index adjusted_serious adjusted_slight injury_based
#> 1  200401BS00001        0.2392801       0.7607199            0
#> 2  200401BS00002        1.0000000       0.0000000            0
#> 3  200401BS00003        0.1029629       0.8970371            0
#> 4  200401BS00004        0.1869999       0.8130001            0
#> 5  200401BS00006        1.0000000       0.0000000            0
#> 6  200401BS00007        1.0000000       0.0000000            0
``` 
`accident_index` are the unique ID(s) of each accident (the same ID(s) reported in STATS19 data). Adjusted_serious and adjusted_slight represent the probabilities that a given car crash is classified as serious or slight, respectively, considering the CRASH methodology and a logistic regression model (see DfT report). Injury_based is a dummy variable that represents if a given car crash was evaluated using an injury_based classification system such as CRASH (and, in that case, the P are either 0 or 1). For example
``` r
head(adj_figures[which(adj_figures$injury_based == 1), ])
#>         accident_index adjusted_serious adjusted_slight injury_based
#> 1502386  2012450000002                0               1            1
#> 1502387  2012450000003                0               1            1
#> 1502388  2012450000004                0               1            1
#> 1502389  2012450000005                0               1            1
#> 1502390  2012450000006                0               1            1
#> 1502391  2012450000032                1               0            1
``` 
(Left-)merge the two data.frame, the common column is accident_index
``` r
crashes_data <- merge(crashes_data, adj_figures, all.x = TRUE, by = "accident_index")

# plot results (just to give a graphical idea of the model)
ggplot(crashes_data) + 
  geom_histogram(
    aes(x = adjusted_serious, fill = accident_severity, group = accident_severity), 
    bins = 100
  ) + 
  theme(legend.position = "bottom")
#> Warning: Removed 1637 rows containing non-finite values (stat_bin).
```

![](https://i.imgur.com/ge4Djyc.png)
The 1637 missing rows are related to the fatal crashes (since, clearly, there is no arbitrary classification in those cases). Indeed,
``` r
table(crashes_data$accident_severity)
#> 
#>   Fatal Serious  Slight 
#>    1637   20901  123033
```
The previous plot means that there is a non-negligible percentage of "Slight" crashes that could be treated as Serious crashes. I would like the explore the methodological consequences of this problem after submitting the thesis.

<sup>Created on 2020-11-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Robinlovelace** [comment]
Very interesting @agila5, many thanks. Heads-up @joeytalbot and @PublicHealthDataGeek, that should make our session on this next week a breeze.

**Comment by Robinlovelace** [comment]
And what do people think about adding a function to `stats19`? One to discuss.

**Comment by PublicHealthDataGeek** [comment]
Excellent!  Looks very good @agila5 .  I have just had a quick pick at the zip file.  So there is one spreadsheet tthat links the  adjustment probabilities to the the `accident_index` and the other one that links them to the `accident_index` plus the `vehicle_reference` and the `casualty_reference`.  I would suggest that would be two function for `stats19` but extremely useful functions to add to the package.

**Comment by Robinlovelace** [comment]
Agreed, solving the problem for everyone isn't much extra effort compared with the effort of solving it for us. And could enable time saved on data cleaning to be spent doing research that could save lives!

**Comment by agila5** [comment]
IMO the only difficult component is how to "ship" the adjustment figures within the package since the ZIP file is approximately 90MB (unless you want to add a function that points to the URL and download the ZIP file each time)

**Comment by Robinlovelace** [comment]
> IMO the only difficult component is how to "ship" the adjustment figures within the package since the ZIP file is approximately 90MB (unless you want to add a function that points to the URL and download the ZIP file each time)

Wouldn't it be the same principle as downloading the other files with `get_stats19()`? I could envisage a function called `get_stats19_adjustments()` or similar.

**Comment by agila5** [comment]
> Wouldn't it be the same principle as downloading the other files with get_stats19()? I could envisage a function called get_stats19_adjustments() or similar.

Well, actually yes... Nevermind 😅
