### ISSUE TITLE
Full STATS19 data querying options: Mongodb V R.data.table

### ISSUE THREAD

**Issue by layik** [saferactive/saferactive#70]
I know we have a 64gb machine and I think we can hold every STATS19 record in its cache/memory. We know reloading this takes at least minutes after any downtime. In the best case, chopping up the data or replicating it on several machines can be costly in the long run (environmentally too).

So, one option is to hold everything in a Mongodb instance, which gives us enough [geosptial](https://docs.mongodb.com/manual/geospatial-queries/) querying capabilities or a PostGIS if latter outperforms former. However, as we have not tested this and personally I do not know what are the production caveats/pitfalls of similar amount of data, we need a basic comparison.

Therefore, I have been working on this and will send the script as soon as ready. This ticket is to document this benchmarking/study.

**Comment by layik** [comment]
1. Loading `8511625` crashes into a Docker container instance of Mongodb on a 16GB MBP (MacBook Pro):

```r
class(m)
[1] "mongo"       "jeroen"      "environment"
nrow(acc)
[1] 8511625
system.time(m$insert(acc))
    user   system  elapsed 
 409.407   59.033 1024.495 
```

2. Creating a `geospatial index` on Mongodb instance using:

```sh
db.stats19.find().forEach(
  function (e) {
    // update document, using its own properties
    e.coords = {
      northing: e.location_easting_osgr,
      easting: e.location_northing_osgr };

    // remove old properties
    delete e.location_easting_osgr;
    delete e.location_northing_osgr;

    // save the updated document
    db.stats19.save(e);
  }
)```
takes `` minutes.

3. Adding all casualties and vehicles data into each record takes `??` minutes

This comment will/was be updated.

**Comment by Robinlovelace** [comment]
My vote: `data.table`.

**Comment by layik** [comment]
Agreed to retire.
